services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: dataops-api
    depends_on:
      - qdrant
    ports:
      - "8000:8000"
    env_file: .env
    networks:
      - dataops-network

  ui:
    build:
      context: ./ui
      dockerfile: ../Dockerfile.ui
    container_name: dataops-ui
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_USE_MOCKS=false
    depends_on:
      - api
    networks:
      - dataops-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: dataops-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - dataops-network


networks:
  dataops-network:
    driver: bridge

volumes:
  qdrant_data:
